server.port: 9005
spring:
  application:
    name: taco-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: taco-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  taco-board-article-service:
    url: http://127.0.0.1:9000
  taco-board-comment-service:
    url: http://127.0.0.1:9001
  taco-board-like-service:
    url: http://127.0.0.1:9002
  taco-board-view-service:
    url: http://127.0.0.1:9003
